Add node-fetch custom agent support
adobe/jwt-auth pull request #51
Opened 2021-03-29 14:32 UTC by mutaphysis

Add node-fetch custom agent support

## Description

Adds a new `agent` property to the options object that
allows configuring the node fetch agent. This can be used
for adding proxy support, doing custom dns resolving and
other advanced use cases.

See https://nodejs.org/api/http.html#http_new_agent_options for
more information on http agents.

## Related Issue

https://github.com/adobe/jwt-auth/issues/50

## Motivation and Context

Will working on a project we had a problem that the back-end we deployed was only allowed network access through a proxy. For our own use of node-fetch this was easily fixed by using a configured https://www.npmjs.com/package/https-proxy-agent but this behaviour was not exposed through the APIs of @adobe/jwt-auth. Thus a simple fix, expose the node-fetch agent property in the API and pass the value through..

## How Has This Been Tested?

Tested with a custom proxy aware agent against mitmproxy & a proprietary company proxy. Test cases have not been changed, test coverage is still at 100%, but there is no real test that the agent is actually passed. Typescript types have been extended.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-04-13 07:08 UTC, mutaphysis commented
Is there a way to retrigger travis, seems stuck to me.

2021-04-23 01:05 UTC, macdonst commented
@mutaphysis sorry for not responding for so long. We switched from TravisCI to GitHub Actions and all the tests are now passing. Can you re-base your PR up to the latest code? Also, it would be awesome if you could update the docs as well.

2022-03-09 13:17 UTC, shazron requested changes

2022-03-09 13:17 UTC, shazron commented on index.d.ts
> +import { Agent } from 'http'
you can also have a https.Agent

2022-03-09 13:17 UTC, shazron commented on index.js
> +    agent
technically node-fetch custom agent can take in a function as well (see node-fetch docs)
Documentation is missing in README.md regarding the agent option.

2022-03-18 16:02 UTC, closed without merging